[default.probe]
usb_vid = "1fc9"
usb_pid = "0132"
# You need to update this to match your own hardware. See README.md for more
# information.
serial  = "11020031"

[default.general]
chip = "LPC845M301JHI48"

[default.rtt]
enabled = true
